// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtmW9Xt-2DnDg6QxY1jpm2r6r98asFi_w',
    appId: '1:936736917986:web:315171050a67e61553d1bb',
    messagingSenderId: '936736917986',
    projectId: 'project-17fc2',
    authDomain: 'project-17fc2.firebaseapp.com',
    storageBucket: 'project-17fc2.firebasestorage.app',
    measurementId: 'G-TE0XH8QMJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzcAkOnZhK_92wHsX6JV8GgvP_yV0BROQ',
    appId: '1:936736917986:android:423c35397997045c53d1bb',
    messagingSenderId: '936736917986',
    projectId: 'project-17fc2',
    storageBucket: 'project-17fc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_wmljGFGT9UCmfgGHQc0oq6u7T7M4xTM',
    appId: '1:936736917986:ios:e190e883f31435b353d1bb',
    messagingSenderId: '936736917986',
    projectId: 'project-17fc2',
    storageBucket: 'project-17fc2.firebasestorage.app',
    iosBundleId: 'com.example.logisticApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_wmljGFGT9UCmfgGHQc0oq6u7T7M4xTM',
    appId: '1:936736917986:ios:e190e883f31435b353d1bb',
    messagingSenderId: '936736917986',
    projectId: 'project-17fc2',
    storageBucket: 'project-17fc2.firebasestorage.app',
    iosBundleId: 'com.example.logisticApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtmW9Xt-2DnDg6QxY1jpm2r6r98asFi_w',
    appId: '1:936736917986:web:76f7d702b6c927e353d1bb',
    messagingSenderId: '936736917986',
    projectId: 'project-17fc2',
    authDomain: 'project-17fc2.firebaseapp.com',
    storageBucket: 'project-17fc2.firebasestorage.app',
    measurementId: 'G-VK6DPNNHF3',
  );
}
